language: android

android:
  components:
    - tools
    - tools  # 2x tools to make sure the latest version gets installed.
    - platform-tools
    - build-tools-24.0.1
    - android-24
    - extra-android-support
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check

after_failure:
  - "cat /home/travis/build/benoitdion/ln/ln/build/outputs/lint-results-debug.xml"
